package com.planner.backend.chat;

import java.util.List;

/**
 * A Java Record that represents the final response sent back to the frontend.
 * 
 * @param text    The conversational text response generated by the AI (e.g., "I have assigned Pasta to Monday.")
 * @param actions A list of structured actions (AiAction) that the frontend React application will read
 *                to update the visual meal planner board on the screen.
 */
public record ChatResponse(String text, List<AiAction> actions) {}
