spring.application.name=meal-planner-backend
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/menudb

# Cambiamos 'update' por 'validate' para que Hibernate valide la BD que crea Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Activa Flyway para ejecutarse automáticamente al iniciar la app
spring.flyway.enabled=true

# Mostrar las consultas SQL en la consola (ideal para aprender)
spring.jpa.properties.hibernate.format_sql=true

# Enabled endpoints for debugging (temporal)
management.endpoints.web.exposure.include=mappings

# Gemini API Key
gemini.api-key=${GEMINI_API_KEY:demo}